name: Rebase Develop on Main

on:
  workflow_run:
    workflows: ["Release Please"]
    types:
      - completed

permissions:
  contents: write

jobs:
  rebase-develop:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
      - name: Rebase develop on main
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git fetch origin main
          git rebase origin/main
          git push --force-with-lease origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
