name: Release Please Develop

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          default-branch: develop
          prerelease: true
          prerelease-type: dev
          bump-minor-pre-major: false
          bump-patch-for-minor-pre-major: false
          release-as: minor