name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: main

      # Check out the repository
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.pr }}

      # Auto-rebase the release PR
      - name: Auto-rebase release PR
        if: ${{ steps.release.outputs.pr }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ steps.release.outputs.pr }}
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git rebase origin/main
          git push --force-with-lease

      # Create GitHub Release
      - name: Create GitHub Release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.release.outputs.tag_name }} \
            --title "Release Candidate ${{ steps.release.outputs.tag_name }}" \
            --notes "${{ steps.release.outputs.changelog }}" \
            --prerelease